services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    ports: 
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka 
    ports:
      # Kafka internal port
      - "9092:9092"
      # Kafka external port (for kafka ui and clients)
      - "29092:29092"
    depends_on: 
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092, PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092, PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on: 
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
  
  spark:
    image: bitnami/spark:3.4.1
    container_name: spark
    depends_on:
      - kafka
    environment:
      - SPARK_MODE=master
    ports:
      - "4040:4040"
    volumes:
      - ./spark:/opt/spark
      - ./minio_data:/mnt/minio  # Spark will write here as if it's S3
      - /tmp:/tmp
  
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"    # S3 Compatible Endpoint
      - "9001:9001"    # MinIO Console
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: samarth108
    command: server /data --console-address ":9001"
    
    